data:
  source: csv
  path: data/EURUSD_1m_sample.csv
  symbol: EURUSD
  timeframe: 1m
  date_format: '%Y-%m-%d %H:%M:%S'
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume
execution:
  broker: paper
  risk:
    model: atr
    risk_per_trade: 0.005
    atr_period: 14
    sl_atr_multiple: 1.5
    tp_rr: 2.0
    min_position: 0.01
    max_position_pct: 0.1
  broker_config:
    initial_balance: 10000.0
    commission_per_trade: 0.0
walk_forward:
  folds: 3
  train_fraction: 0.6
  overlap_fraction: 0.1
sweep:
  enabled: false
  parameters: {}
  n_trials: 100
strategy:
  name: htf_liquidity_mtf
  symbol: EURUSD
  htf_list:
  - H1
  - H4
  - D1
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.5
    killzone:
    - '12:00'
    - '14:05'
    regime_ok:
    - bull
    - neutral
indicators:
  ema21_period: 21
  ema50_period: 50
  atr_period: 14
  volume_sma_period: 20
  regime_sensitivity: 0.001
aggregation:
  source_tf_minutes: 1
  target_timeframes_minutes:
  - 60
  - 240
  - 1440
  buffer_size: 1500
  roll_from: source
  max_candles_per_update: 10
  enable_streaming: true
  out_of_order_policy: drop
  max_clock_skew_seconds: 300
  enable_strict_ordering: true
detectors:
  fvg:
    min_gap_atr: 0.3
    min_gap_pct: 0.05
    min_rel_vol: 1.2
  pivot:
    lookback: 5
    min_sigma: 0.5
  indicators:
    atr_period: 14
    volume_sma_period: 20
  out_of_order_policy: drop
  enabled_timeframes:
  - H1
  - H4
  - D1
pools:
  H1:
    ttl: 120m
    hit_tolerance: 0.0
  H4:
    ttl: 6h
    hit_tolerance: 0.0
  D1:
    ttl: 2d
    hit_tolerance: 0.0
  strength_threshold: 0.1
  grace_period_minutes: 5
  max_pools_per_tf: 10000
  auto_expire_interval: 30s
hlz:
  min_members: 2
  min_strength: 3.0
  tf_weight:
    H1: 1.0
    H4: 2.0
    D1: 3.0
  merge_tolerance: 0.5
  side_mixing: false
  max_active_hlzs: 1000
  recompute_on_update: true
zone_watcher:
  price_tolerance: 0.0
  confirm_closure: false
  min_strength: 1.0
  max_active_zones: 1000
candidate:
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.2
    killzone:
    - '12:00'
    - '14:05'
    regime:
    - bull
    - neutral
feeds:
  base_tf: 1m
  source: csv
