# Ruff configuration for algorithmic trading project
target-version = "py311"
line-length = 88

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "RUF", # ruff-specific rules
]

ignore = [
    "E501",   # line too long (handled by formatter)
    "B008",   # do not perform function calls in argument defaults
    "F401",   # unused imports (common in module interfaces)
    "RUF002", # docstring contains ambiguous characters
    "RUF015", # unnecessary iterable allocation for first element
    "RUF022", # __all__ sorting
]

[lint.per-file-ignores]
"tests/*" = [
    "F401",   # unused imports in test files
    "F811",   # redefined names in tests
    "S101",   # assert statements are expected in tests
]

"debug_*.py" = [
    "B007",   # unused loop variables
    "F841",   # unused variables
    "SIM105", # simplify try-except-pass
]

"test_*.py" = [
    "F401",   # unused imports in test files
    "F841",   # unused variables in tests
    "B007",   # unused loop variables
]
