"""create fvg table

Revision ID: dafc562b5f25
Revises: 
Create Date: 2025-07-14 00:29:45.095283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafc562b5f25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fvg',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('zone_low', sa.Float(), nullable=False),
    sa.Column('zone_high', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('iFVG', sa.Boolean(), nullable=True),
    sa.Column('touched', sa.Boolean(), nullable=True),
    sa.Column('created_by_index', sa.Integer(), nullable=True),
    sa.Column('mitigation_by', sa.Integer(), nullable=True),
    sa.Column('invalidated_by', sa.Integer(), nullable=True),
    sa.Column('mitigated_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.Column('retested', sa.Boolean(), nullable=True),
    sa.Column('retested_at', sa.DateTime(), nullable=True),
    sa.Column('penetration_pct', sa.Float(), nullable=True),
    sa.Column('duration_open', sa.Integer(), nullable=True),
    sa.Column('volume_at_creation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fvg')
    # ### end Alembic commands ###
