# Balanced FVG and Zone Watcher Configuration
# Based on analysis of current settings and best practices

# CURRENT vs RECOMMENDED COMPARISON:
#
# FVG DETECTION:
# Current:    min_gap_atr: 0.05 (VERY_HIGH sensitivity - catches micro-gaps)
# Balanced:   min_gap_atr: 0.2  (Balanced - significant gaps only)
#
# Current:    min_gap_pct: 0.01 (1% gaps - very small movements)
# Balanced:   min_gap_pct: 0.03 (3% gaps - meaningful movements)
#
# Current:    min_rel_vol: 0.0  (DISABLED - accepts any volume)
# Balanced:   min_rel_vol: 1.5  (50% above average - quality filter)
#
# Current:    strength_threshold: 0.35 (LOW quality filter)
# Balanced:   strength_threshold: 0.4   (Balanced quality filter)
#
# ZONE WATCHER:
# Current:    min_strength: 0.01 (TOO LOW - tracks very weak zones)
# Balanced:   min_strength: 0.3  (Balanced - meaningful strength)
#
# Current:    price_tolerance: 0.0  (Exact hits only)
# Balanced:   price_tolerance: 0.1  (Slight tolerance for noise)

# BALANCED CONFIGURATION FOR H4 SWING TRADING
detectors:
  fvg:
    # Balanced sensitivity - catches significant gaps without noise
    min_gap_atr: 0.2 # 20% of ATR (vs current 5%)
    min_gap_pct: 0.03 # 3% price gap (vs current 1%)
    min_rel_vol: 1.5 # 50% above average volume (vs disabled)

  pivot:
    # Keep existing pivot settings (these look reasonable)
    lookback: 5
    min_strength: 0.01

pools:
  # Balanced quality filter
  strength_threshold: 0.4 # Slightly higher than current 0.35

zone_watcher:
  # Balanced zone tracking
  price_tolerance: 0.1 # Allow slight tolerance for market noise
  min_strength: 0.3 # Much higher than current 0.01
  max_active_zones: 1000 # Keep current capacity
  confirm_closure: false # Keep immediate entry

candidate:
  # Balanced timing for H4 swing trading
  expiry_minutes: 180 # 3 hours (vs current 2 hours)
  min_entry_spacing_minutes: 45 # 45 minutes (vs current 30)

# ALTERNATIVE CONFIGURATIONS FOR DIFFERENT SCENARIOS:

# FOR VOLATILE MARKETS:
# detectors:
#   fvg:
#     min_gap_atr: 0.15    # More sensitive for volatile conditions
#     min_gap_pct: 0.025   # Lower percentage threshold
#     min_rel_vol: 1.8     # Higher volume requirement for confirmation
# pools:
#   strength_threshold: 0.45  # Higher quality in volatile markets

# FOR RANGING MARKETS:
# detectors:
#   fvg:
#     min_gap_atr: 0.25    # Less sensitive in ranging markets
#     min_gap_pct: 0.04    # Higher percentage threshold
#     min_rel_vol: 1.3     # Lower volume requirement
# pools:
#   strength_threshold: 0.35  # Lower quality threshold for more signals

# FOR SCALPING (H1):
# zone_watcher:
#   price_tolerance: 0.05
#   min_strength: 0.2
# candidate:
#   expiry_minutes: 120    # 2 hours
#   min_entry_spacing_minutes: 30

# FOR POSITION TRADING (D1):
# zone_watcher:
#   price_tolerance: 0.2
#   min_strength: 0.6      # Much higher strength for daily
# candidate:
#   expiry_minutes: 720    # 12 hours
#   min_entry_spacing_minutes: 180  # 3 hours

# KEY BALANCE PRINCIPLES:
# 1. FVG Sensitivity: Balance between catching opportunities and avoiding noise
# 2. Volume Filtering: Confirms momentum behind price movements
# 3. Strength Thresholds: Filter for quality zones and signals
# 4. Timing Parameters: Match your trading timeframe and style
# 5. Zone Tolerance: Allow for market microstructure noise

# RECOMMENDED PROGRESSION:
# 1. Start with balanced settings above
# 2. Monitor signal quality vs quantity for 1 week
# 3. Adjust based on market conditions:
#    - Increase sensitivity in ranging markets
#    - Decrease sensitivity in volatile markets
#    - Adjust volume filtering based on data quality
# 4. Fine-tune strength thresholds based on backtest results
