strategy:
  name: htf_liquidity_mtf
  htf_list: ["H1", "H4", "D1"]
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.5
    killzone: ["12:00", "14:05"]
    regime_ok: ["bull", "neutral"]

indicators:
  ema21_period: 21
  ema50_period: 50
  atr_period: 14
  volume_sma_period: 20
  regime_sensitivity: 0.001

aggregation:
  # Source timeframe and target timeframes for multi-timeframe analysis
  source_tf_minutes: 1 # 1-minute source data
  target_timeframes_minutes: [60, 240, 1440] # H1, H4, D1
  buffer_size: 1500 # Ring buffer size for memory efficiency

  # Aggregation strategy
  roll_from: "source" # "source" = from-scratch aggregation, "lower_tf" = H1→H4 chaining

  # Performance settings
  max_candles_per_update: 10 # Batch processing limit
  enable_streaming: true # Real-time vs batch mode

execution:
  broker: paper
  risk_per_trade: 0.005

feeds:
  base_tf: 1m
  source: csv
