strategy:
  name: htf_liquidity_mtf
  htf_list: ["H1", "H4", "D1"]
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.5
    killzone: ["12:00", "14:05"]
    regime_ok: ["bull", "neutral"]

indicators:
  ema21_period: 21
  ema50_period: 50
  atr_period: 14
  volume_sma_period: 20
  regime_sensitivity: 0.001

aggregation:
  # Source timeframe and target timeframes for multi-timeframe analysis
  source_tf_minutes: 1 # 1-minute source data
  target_timeframes_minutes: [60, 240, 1440] # H1, H4, D1
  buffer_size: 1500 # Ring buffer size for memory efficiency

  # Aggregation strategy
  roll_from: "source" # "source" = from-scratch aggregation, "lower_tf" = H1→H4 chaining

  # Performance settings
  max_candles_per_update: 10 # Batch processing limit
  enable_streaming: true # Real-time vs batch mode

  # Clock-skew and ordering policies
  out_of_order_policy: "drop" # "drop", "raise", or "recalc"
  max_clock_skew_seconds: 300 # Maximum allowed time drift (5 minutes)
  enable_strict_ordering: true # Enforce chronological order

detectors:
  fvg:
    min_gap_atr: 0.3 # Minimum gap size in ATR units
    min_gap_pct: 0.05 # Minimum gap size as percentage (5%)
    min_rel_vol: 1.2 # Minimum volume relative to SMA

  pivot:
    lookback: 5 # Lookback periods for pivot detection (3-10)
    min_sigma: 0.5 # Minimum ATR distance for confirmation

  indicators:
    atr_period: 14 # ATR calculation period
    volume_sma_period: 20 # Volume SMA baseline period

  # Ordering policy for out-of-sequence HTF candles
  out_of_order_policy: "drop" # "drop" or "raise"

  enabled_timeframes: ["H1", "H4", "D1"] # Active detection timeframes

execution:
  broker: paper
  risk_per_trade: 0.005

feeds:
  base_tf: 1m
  source: csv
