# =========================
#  Back-test master config
# =========================

# ---------- Data ----------
data:
  source: csv
  path: "data/BTC_USD_5min_20250728_021825.csv"
  symbol: BTCUSD
  timeframe: "5m"
  date_format: "%Y-%m-%dT%H:%M:%SZ"
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume

# ---------- Walk-forward ----------
walk_forward:
  folds: 3
  train_fraction: 0.5
  overlap_fraction: 0.1

# ---------- Sweep (disabled here) ----------
sweep:
  enabled: false
  parameters: {}
  n_trials: 100
  max_workers: 4

# ---------- Strategy core ----------
strategy:
  name: htf_liquidity_mtf
  symbol: BTCUSD
  use_mock_strategy: false # Set to true for simple EMA mock, false for full HTF system
  htf_list: ["H4", "D1"] # only H4 & D1 liquidity pools
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.5
    killzone: ["01:00", "18:00"] # Asia start to NY end (covers all major sessions)
    regime_ok: ["bull", "neutral"]

# ---------- Indicator periods ----------
indicators:
  ema21_period: 21
  ema50_period: 50
  atr_period: 14
  volume_sma_period: 20
  regime_sensitivity: 0.001

# ---------- Aggregation ----------
aggregation:
  source_tf_minutes: 5 # feed resolution
  target_timeframes_minutes: [240, 1440] # H4, D1 only (removed H1 for FVG-only strategy)
  buffer_size: 1500
  roll_from: "source"
  out_of_order_policy: "drop"
  max_clock_skew_seconds: 300
  enable_strict_ordering: true
  fill_missing: "ffill" # Forward-fill missing time slots to regularize EMA/ATR computation

# ---------- Detectors ----------
detectors:
  fvg:
    enabled: true
    min_gap_atr: 0.1 # REDUCED from 0.3 - less strict ATR requirement
    min_gap_pct: 0.03 # REDUCED from 0.05 - less strict percentage requirement
    min_rel_vol: 1.0 # REDUCED from 1.2 due to poor volume data quality

  pivot:
    enabled: false # ← pivot detector OFF

  enabled_timeframes: ["H4", "D1"]

# ---------- Pool registry ----------
pools:
  H4:
    ttl: 3d # 3 days for H4 pools
    hit_tolerance: 0.0
  D1:
    ttl: 3w # 3 weeks for D1 pools
    hit_tolerance: 0.0

  strength_threshold: 0.05
  grace_period_minutes: 5
  max_pools_per_tf: 10000
  auto_expire_interval: "30s"

# ---------- HLZ overlap ----------
hlz:
  min_members: 2
  min_strength: 3.0
  tf_weight:
    H4: 2.0
    D1: 3.0
  merge_tolerance: 0.5
  side_mixing: false
  max_active_hlzs: 1000
  recompute_on_update: true

# ---------- Zone watcher & FSM ----------
zone_watcher:
  price_tolerance: 0.0
  confirm_closure: false
  min_strength: 1.0
  max_active_zones: 1000

# ---------- Signal candidate pipeline ----------
candidate:
  expiry_minutes: 120
  filters:
    ema_alignment: true
    ema_tolerance_pct: 0 # EMA tolerance buffer (0.2% flexibility)
    linger_minutes: 90 # Touch-&-reclaim linger window (minutes) - INCREASED from 60
    reclaim_requires_ema: true # Require EMA flip after zone touch
    volume_multiple: 0 # DISABLED due to poor volume data quality (0 = no volume filter)
    killzone: ["01:00", "18:00"] # Asia start to NY end (covers all major sessions)
    regime: ["bull", "neutral"]

# ---------- Execution (Paper back-test) ----------
execution:
  mode: backtest # live | backtest (live requires feeds.source = websocket)
  broker: paper
  log_level: DEBUG # Enable debug logging to see signal rejection reasons
  enable_latency_profiling: true
  enable_memory_tracking: true
  realtime_simulation: false # batch back-test
  deterministic_seed: 42
  dump_events: false # disable events.parquet export for production runs (was creating 6k events)
  export_data_for_viz: true # enable data.csv and trades.csv export
  risk:
    model: atr
    risk_per_trade: 0.005
    atr_period: 14
    sl_atr_multiple: 1.5
    tp_rr: 2.0
    min_position: 0.01
    max_position_pct: 0.1
  broker_config:
    initial_balance: 10000.0
    commission_per_trade: 0.0

# ---------- Feed layer ----------
feeds:
  base_tf: 5m
  source: csv
