# =========================
#  Binance Historical Data Config
# =========================

# ---------- Data ----------
data:
  source: csv
  path: "data/BTC_USD_5min_20250801_001617.csv"
  symbol: BTCUSDT
  tick_size: 0.01 # Price precision for BTCUSDT
  timeframe: "5m"
  date_format: "%Y-%m-%dT%H:%M:%SZ"
  start_date: "2024-05-01" # Start with May 2024
  end_date: "2024-08-01" # 3 months: May, June, July 2024
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume

# ---------- Walk-forward ----------
walk_forward:
  folds: 3 # 3 folds = 1 month per fold for 3 months
  train_fraction: 0.6 # 60% for training, 40% for testing (gives ~18 days train, 12 days test per month)
  overlap_fraction: 0.1 # 10% overlap between folds

# ---------- Sweep (disabled here) ----------
sweep:
  enabled: false
  parameters: {}
  n_trials: 100
  max_workers: 4

# ---------- Strategy core ----------
strategy:
  name: htf_liquidity_mtf
  symbol: BTCUSDT
  use_mock_strategy: false # Set to true for simple EMA mock, false for full HTF system
  htf_list: ["60", "240", "1440"] # Multi-timeframe: 60min (H1) + 240min (H4) + 1440min (D1) for maximum confluence

# ---------- Risk Management ----------
risk:
  model: atr
  risk_per_trade: 0.005
  atr_period: 14
  sl_atr_multiple: 1.5
  tp_rr: 3
  min_position: 0.01
  max_position_pct: 0.1

# ---------- Indicator periods ----------
indicators:
  ema21_period: 21
  ema50_period: 50
  atr_period: 14
  volume_sma_period: 20
  regime_sensitivity: 0.001

# ---------- Aggregation ----------
aggregation:
  source_tf_minutes: 5 # feed resolution
  target_timeframes_minutes: [60, 240, 1440] # H1 (60min) + H4 (240min) + D1 (1440min) for multi-timeframe analysis
  buffer_size: 1500
  roll_from: "calendar" # FIXED: Align to proper 4H boundaries (00:00, 04:00, 08:00, 12:00, 16:00, 20:00)
  out_of_order_policy: "drop"
  max_clock_skew_seconds: 300
  enable_strict_ordering: true
  fill_missing: "ffill" # Forward-fill missing time slots (less needed with Binance data)

# ---------- Detectors ----------
detectors:
  fvg:
    enabled: true
    min_gap_atr: 0.2 # MORE SENSITIVE - reduced from 0.2
    min_gap_pct: 0.03 # MORE SENSITIVE - reduced from 0.04
    min_rel_vol: 1.5 # COMPLETELY DISABLED - no volume filter

  pivot:
    enabled: true # ENABLED to detect significant pivot points
    lookback_period: 5 # Number of candles to look back/forward for pivot confirmation
    min_atr_distance: 1.0 # Minimum ATR distance from previous pivot
    strength_calc: "atr_based" # Use ATR-based strength calculation

  enabled_timeframes: ["60", "240", "1440"] # H1 (60min) + H4 (240min) + D1 (1440min) for multi-timeframe detection

# ---------- Pool registry ----------
pools:
  "60": # 60min (H1) pools for confluence only (not standalone entries)
    ttl: 6h # 6 hours for H1 pools (shorter than H4)
    hit_tolerance: 0.0
  "240": # 240min (H4) pools for both standalone and confluence
    ttl: 3d # 3 days for H4 pools
    hit_tolerance: 0.0
  "1440": # 1440min (D1) pools for major structural confluence
    ttl: 3w # 3 weeks for D1 pools (longest timeframe)
    hit_tolerance: 0.0

  strength_threshold: 0.5 # BALANCED - filters weak signals while capturing quality FVGs (0.5+ range)
  grace_period_minutes: 5
  max_pools_per_tf: 10000
  auto_expire_interval: "30s"

# ---------- Pivot Pools ----------
pivot_pools:
  "60": # 60min (H1) pivot pools for short-term structure
    ttl: 12h # 12 hours for H1 pivot pools
    hit_tolerance: 0.0
    min_atr_distance: 0.8 # Slightly lower for H1 timeframe
  "240": # 240min (H4) pivot pools for structural analysis
    ttl: 5d # 5 days for H4 pivot pools (longer than FVG pools as pivots are structural)
    hit_tolerance: 0.0
    min_atr_distance: 1.0 # Minimum ATR distance for pivot significance
  "1440": # 1440min (D1) pivot pools for major structural levels
    ttl: 1M # 1 month for D1 pivot pools (major swing levels)
    hit_tolerance: 0.0
    min_atr_distance: 1.5 # Higher distance for daily pivots

  strength_threshold: 0.5 # Higher threshold for pivots as they should be significant levels
  grace_period_minutes: 10 # Longer grace period for pivot validation
  max_pools_per_tf: 5000 # Fewer pivot pools as they're less frequent but more significant
  auto_expire_interval: "60s" # Longer interval for pivot pool cleanup

# ---------- HLZ overlap ----------
hlz:
  min_members: 2 # Require at least 2 overlapping pools for HLZ
  min_strength: 3.0 # Threshold for multi-timeframe confluence (H1+H4+D1 combinations)
  tf_weight:
    "60": 1.0 # 60min (H1) base weight for confluence contribution only
    "240": 2.5 # 240min (H4) higher weight for structural importance
    "1440": 4.0 # 1440min (D1) highest weight for major structural levels
  merge_tolerance: 0.3 # Tighter overlap requirement for precision (was 0.5)
  side_mixing: false
  max_active_hlzs: 500 # Reduced for performance optimization (was 1000)
  recompute_on_update: true

# ---------- Zone watcher & FSM ----------
zone_watcher:
  price_tolerance: 0.1
  confirm_closure: false
  min_strength: 1.0 # Allows H4 (0.4*2.5=1.0≥1.0) and D1 (0.25*4.0=1.0≥1.0) pools while limiting H1 standalone
  max_active_zones: 500 # Reduced for performance with higher quality zones (was 1000)

# ---------- Signal candidate pipeline ----------
candidate:
  expiry_minutes: 120 # 2 hours - appropriate for signal candidate lifetime

  # Entry spacing to prevent rapid-fire trades
  min_entry_spacing_minutes: 45 # Per-pool minimum spacing (45 minutes)
  global_min_entry_spacing: 30 # Increased global spacing for better quality (was 15)
  enable_spacing_throttle: true # Enable throttling mechanism

  filters:
    ema_alignment: true
    ema_tolerance_pct: 0 # Slightly more tolerance with real data
    linger_minutes: 60 # Touch-&-reclaim linger window (minutes)
    reclaim_requires_ema: true # Require EMA flip after zone touch
    volume_multiple: 3 # ENABLED - re-enabled with quality data

    # Enhanced killzone settings (replaces legacy killzone: ["01:00", "18:00"])
    use_enhanced_killzone: true # Enable multi-session killzone system
    killzone_sessions: ["asia", "london", "ny"] # All major trading sessions
    exclude_low_volume: true # Exclude 00:00-02:00 and 05:00-07:00 UTC low-volume periods

    # Legacy killzone settings (kept for backward compatibility)
    killzone: ["01:00", "18:00"] # Extended killzone to ensure May 20 14:00-18:00 window is included

    regime: ["bear", "bull"] # ALL regimes allowed

    # ALTERNATIVE KILLZONE CONFIGURATIONS:
    # For Asia-only strategy: killzone_sessions: ["asia"]
    # For London-only strategy: killzone_sessions: ["london"]
    # For NY-only strategy: killzone_sessions: ["ny"]
    # For London+NY overlap: killzone_sessions: ["london", "ny"]
    # To allow low-volume periods: exclude_low_volume: false

# ---------- Execution (Paper back-test) ----------
execution:
  mode: backtest # live | backtest (live requires feeds.source = websocket)
  broker: paper
  log_level: INFO # Reduced logging for better performance during walk-forward
  enable_latency_profiling: false # Disabled for faster execution
  enable_memory_tracking: false # Disabled for faster execution
  realtime_simulation: false # batch back-test
  deterministic_seed: 42
  dump_events: true # ENABLED for enhanced analysis - exports event data
  export_data_for_viz: true # ENABLED for enhanced analysis - exports market data and trade data

  # Slippage configuration for realistic execution simulation
  slippage:
    entry_pct: 0.0002 # 0.02% worse than market price on entry (2 bps)
    exit_pct: 0.0002 # 0.02% worse than market price on exit (2 bps)
    # Alternative models (for future implementation):
    # model: "fixed_pct"  # Options: "fixed_pct", "fixed_ticks", "atr_based"
    # atr_multiplier: 0.1  # For ATR-based slippage: slippage = ATR * 0.1

  broker_config:
    name: binance
    testnet: true # explicit testnet flag
    initial_balance: 10000.0
    commission_per_trade: 0.0004 # Binance Futures taker fee: 0.04% (realistic for market orders)
    # commission_per_trade: 0.0002 # Binance Futures maker fee: 0.02% (if using limit orders)
    # Connection and rate limiting settings
    ws_timeout: 30 # WebSocket timeout in seconds
    rest_timeout: 10 # REST API timeout in seconds
    max_retries: 3 # Maximum retry attempts for failed requests
    retry_backoff: 1.0 # Backoff multiplier for retries
    min_request_interval: 0.1 # Minimum interval between requests (rate limiting)

# ---------- Runtime ----------
runtime:
  use_mock_components: true # Enable mocks for backtesting (disable for live trading)

# ---------- Feed layer ----------
feeds:
  base_tf: 5m
  source: csv
