# =========================
#  Fast 3-Phase Optimization Config for BTC_USD_5min_20250801_180943.csv
#   min_strength  min_strength: 1.0  # Will be   strength_threshold: 0.5  # Will be optimized in range [0.2, 0.8] - More permissiveptimized in range [0.5, 2.0] - More permissive 1.0  # Will be optimized in range [0.8, 3.0] - More permissiveOptimized for speed while maintaining result quality
# =========================

# ---------- Data ----------
data:
  source: csv
  path: "data/BTCUSDT_5m_2025-05-18_futures.csv"
  symbol: BTCUSDT
  tick_size: 0.01
  timeframe: "5m"
  date_format: "%Y-%m-%dT%H:%M:%SZ"
  start_date: "2025-05-01"
  end_date: "2025-07-01"
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume

# ---------- Walk-forward (Reduced for speed) ----------
walk_forward:
  folds: 2 # Reduced from 3 for faster optimization
  train_fraction: 0.6
  overlap_fraction: 0.1

# ---------- Strategy ----------
strategy:
  name: htf_liquidity_mtf
  symbol: BTCUSDT
  use_mock_strategy: false
  htf_list: ["60", "240", "1440"]
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.2
    killzone: ["01:00", "18:00"]
    regime_ok: ["bull", "neutral"]

# ---------- Account ----------
account:
  initial_balance: 10000.0
  currency: USDT

# ---------- Risk (Parameters to optimize) ----------
risk:
  model: fixed_fractional
  risk_per_trade: 0.015 # Will be optimized in range [0.005, 0.025]
  max_positions: 3
  tp_rr: 3.0 # Will be optimized in range [2.0, 4.0]
  sl_atr_multiple: 1.5 # Will be optimized in range [1.0, 2.5]
  enable_trailing_stop: false

# ---------- Execution (Minimal logging) ----------
execution:
  slippage_model: linear
  slippage_bps: 2.0
  commission_rate: 0.0004
  dump_events: false # Disable event dumping for speed
  export_data_for_viz: false # Disable viz export for speed
  enable_latency_profiling: false # Add missing field
  enable_memory_tracking: false # Add missing field

# ---------- Aggregation ----------
aggregation:
  source_tf_minutes: 5
  target_timeframes_minutes: [60, 240, 1440]
  buffer_size: 1500
  roll_from: "calendar"
  out_of_order_policy: "drop"
  max_clock_skew_seconds: 300
  enable_strict_ordering: false # Relaxed for speed
  fill_missing: ffill

# ---------- Indicators ----------
indicators:
  ema:
    periods: [21, 50, 200]
    source: close

  atr:
    period: 14

  volume_sma:
    period: 20

# ---------- Detectors (Parameters to optimize) ----------
detectors:
  fvg:
    enabled: true
    min_gap_atr: 0.3 # Will be optimized in range [0.15, 0.4]
    min_gap_pct: 0.015 # Will be optimized in range [0.01, 0.05]
    min_rel_vol: 0.75 # Will be optimized in range [0.5, 2.5]
    max_age_minutes: 1440
    enabled_timeframes: ["60", "240", "1440"]

  pivot:
    enabled: false

# ---------- HLZ (Parameters to optimize) ----------
hlz:
  min_members: 2
  min_strength: 1.5 # Will be optimized in range [1.5, 4.0]
  tf_weight:
    "60": 1.0
    "240": 2.5
    "1440": 4.0
  merge_tolerance: 0.3 # Will be optimized in range [0.2, 0.5]
  side_mixing: false
  max_active_hlzs: 200 # Reduced for speed
  recompute_on_update: false # Disabled for speed

# ---------- Zone Watcher (Parameters to optimize) ----------
zone_watcher:
  price_tolerance: 0.1
  confirm_closure: false
  min_strength: 0.7 # Will be optimized in range [0.8, 2.5] - Much more permissive
  max_active_zones: 200 # Reduced for speed

# ---------- Signal candidate pipeline ----------
candidate:
  expiry_minutes: 120
  min_entry_spacing_minutes: 45 # Will be optimized in range [30, 120]
  global_min_entry_spacing: 10
  enable_spacing_throttle: true
  filters:
    ema_alignment: true
    ema_tolerance_pct: 0.002 # Will be optimized in range [0.0005, 0.003]
    linger_minutes: 60
    reclaim_requires_ema: true
    volume_multiple: 1.5 # Will be optimized in range [0.0, 3.0]
    use_enhanced_killzone: false
    killzone: ["01:00", "18:00"]
    regime: ["bull", "neutral"]

# ---------- Pool registry (Parameters to optimize) ----------
pools:
  "60":
    ttl: 6h
    hit_tolerance: 0.0
  "240":
    ttl: 3d
    hit_tolerance: 0.0
  "1440":
    ttl: 3w
    hit_tolerance: 0.0

  strength_threshold: 0.3 # Will be optimized in range [0.3, 1.0] - Much more permissive
  grace_period_minutes: 60
  max_pools_per_tf: 1000 # Reduced for speed
  auto_expire_interval: "60s" # Less frequent for speed

# ---------- Pivot Pools ----------
pivot_pools:
  "60":
    ttl: 12h
    hit_tolerance: 0.0
    min_atr_distance: 0.8
  "240":
    ttl: 5d
    hit_tolerance: 0.0
    min_atr_distance: 1.0
  "1440":
    ttl: 1M
    hit_tolerance: 0.0
    min_atr_distance: 1.5

  strength_threshold: 0.5
  grace_period_minutes: 10
  max_pools_per_tf: 1000 # Reduced for speed
  auto_expire_interval: "60s"

# ---------- Confluence ----------
confluence:
  min_score: 2
  factors:
    fvg_touch: 1
    pivot_level: 1
    ema_alignment: 1
    volume_spike: 1
