# =========================
#  Phase 3: Production Validation Config
#  Based on successful diagnostic test + Phase 2 optimization
# =========================

# ---------- Data ----------
data:
  source: csv
  path: "data/BTC_USD_5min_20250801_180943.csv"
  symbol: BTCUSDT
  tick_size: 0.01
  timeframe: "5m"
  date_format: "%Y-%m-%dT%H:%M:%SZ"
  start_date: "2025-05-01"
  end_date: "2025-07-01"
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume

# ---------- Walk-forward ----------
walk_forward:
  folds: 3
  train_fraction: 0.6
  overlap_fraction: 0.1

# ---------- Strategy ----------
strategy:
  name: htf_liquidity_mtf
  symbol: BTCUSDT
  use_mock_strategy: false
  htf_list: ["60", "240", "1440"]
  expiry_minutes: 120
  filters:
    ema_alignment: true
    volume_multiple: 1.2 # Relaxed from default
    killzone: ["01:00", "18:00"]
    regime_ok: ["bull", "neutral"]

  candidate:
    # Entry spacing configuration moved to main candidate section

# ---------- Account ----------
account:
  initial_balance: 10000.0
  currency: USDT

# ---------- Risk (Optimized from Phase 2) ----------
risk:
  model: fixed_fractional
  risk_per_trade: 0.015 # Slightly higher than Phase 2
  max_positions: 3
  tp_rr: 3.0 # Conservative
  sl_atr_multiple: 1.5 # Conservative
  enable_trailing_stop: false

# ---------- Execution ----------
execution:
  slippage_model: linear
  slippage_bps: 2.0
  commission_rate: 0.0004

# ---------- Aggregation ----------
aggregation:
  source_tf_minutes: 5
  target_timeframes_minutes: [60, 240, 1440]
  buffer_size: 1500
  roll_from: "calendar"
  out_of_order_policy: "drop"
  max_clock_skew_seconds: 300
  enable_strict_ordering: true
  fill_missing: ffill

# ---------- Indicators ----------
indicators:
  ema:
    periods: [21, 50, 200]
    source: close

  atr:
    period: 14

  volume_sma:
    period: 20

# ---------- Detectors (Relaxed from Phase 2) ----------
detectors:
  fvg:
    enabled: true
    min_gap_atr: 0.5 # More lenient than Phase 2's 0.3
    min_gap_pct: 0.1 # More lenient than Phase 2's 0.015
    min_rel_vol: 1.0 # More lenient than Phase 2's 0.75
    max_age_minutes: 1440
    enabled_timeframes: ["60", "240", "1440"]

  pivot:
    enabled: false # Disable for now as noted "not implemented yet"
    swing_strength: 3
    min_distance_atr: 2.0

# ---------- HLZ (Relaxed from Phase 2) ----------
hlz:
  min_members: 2
  min_strength: 1 # More lenient than Phase 2's 1.5
  tf_weight:
    "60": 1.0
    "240": 2.5
    "1440": 4.0
  merge_tolerance: 0.5
  side_mixing: false
  max_active_hlzs: 500
  recompute_on_update: true

# ---------- Zone Watcher (Relaxed) ----------
zone_watcher:
  price_tolerance: 0.1
  confirm_closure: false
  min_strength: 0.5 # More lenient than Phase 2's 1.8
  max_active_zones: 500

# ---------- Signal candidate pipeline ----------
candidate:
  expiry_minutes: 120 # 2 hours - appropriate for signal candidate lifetime
  min_entry_spacing_minutes: 30
  global_min_entry_spacing: 10
  enable_spacing_throttle: true
  filters:
    ema_alignment: true # Enable EMA alignment filter
    ema_tolerance_pct: 0.5 # More tolerant
    linger_minutes: 60
    reclaim_requires_ema: true
    volume_multiple: 1.2 # More tolerant
    use_enhanced_killzone: false # Disable enhanced for simplicity
    killzone: ["01:00", "18:00"]
    regime: ["bull", "neutral"]

# ---------- Pool registry ----------
pools:
  "60": # 60min (H1) pools for confluence only (not standalone entries)
    ttl: 6h # 6 hours for H1 pools (shorter than H4)
    hit_tolerance: 0.0
  "240": # 240min (H4) pools for both standalone and confluence
    ttl: 3d # 3 days for H4 pools
    hit_tolerance: 0.0
  "1440": # 1440min (D1) pools for major structural confluence
    ttl: 3w # 3 weeks for D1 pools (longest timeframe)
    hit_tolerance: 0.0

  strength_threshold: 0.5 # More lenient than Phase 2's 0.8
  grace_period_minutes: 60 # Required parameter
  max_pools_per_tf: 10000
  auto_expire_interval: "30s"

# ---------- Pivot Pools ----------
pivot_pools:
  "60": # 60min (H1) pivot pools for short-term structure
    ttl: 12h # 12 hours for H1 pivot pools
    hit_tolerance: 0.0
    min_atr_distance: 0.8
  "240": # 240min (H4) pivot pools for structural analysis
    ttl: 5d # 5 days for H4 pivot pools
    hit_tolerance: 0.0
    min_atr_distance: 1.0
  "1440": # 1440min (D1) pivot pools for major structural levels
    ttl: 1M # 1 month for D1 pivot pools
    hit_tolerance: 0.0
    min_atr_distance: 1.5

  strength_threshold: 0.5
  grace_period_minutes: 10
  max_pools_per_tf: 5000
  auto_expire_interval: "60s"

# ---------- Confluence ----------
confluence:
  min_score: 2
  factors:
    fvg_touch: 1
    pivot_level: 1
    ema_alignment: 1
    volume_spike: 1
