# =========================
#  Ultra-Fast Optimization Config for BTC - Speed-first approach
#  Sacrifices some accuracy for maximum speed
# =========================

# ---------- Data (Smaller subset for ultra-fast testing) ----------
data:
  source: csv
  path: "data/BTCUSDT_5m_2025-05-18_futures.csv"
  symbol: BTCUSDT
  tick_size: 0.01
  timeframe: "5m"
  date_format: "%Y-%m-%dT%H:%M:%SZ"
  start_date: "2025-05-18" # Much smaller date range
  end_date: "2025-05-20" # Only 2 days for ultra-fast testing
  columns:
    timestamp: timestamp
    open: open
    high: high
    low: low
    close: close
    volume: volume

# ---------- Walk-forward (Minimal) ----------
walk_forward:
  folds: 2 # Minimum possible
  train_fraction: 0.7 # Higher training fraction
  overlap_fraction: 0.0 # No overlap for speed

# ---------- Strategy ----------
strategy:
  name: htf_liquidity_mtf
  symbol: BTCUSDT
  use_mock_strategy: false
  htf_list: ["60", "240"] # Removed 1440 to reduce complexity
  expiry_minutes: 60 # Reduced from 120
  filters:
    ema_alignment: false # Disabled for speed
    volume_multiple: 0.0 # Disabled
    killzone: [] # Disabled killzone filtering
    regime_ok: ["bull", "neutral", "bear"] # Accept all

# ---------- Account ----------
account:
  initial_balance: 10000.0
  currency: USDT

# ---------- Risk (Simplified ranges) ----------
risk:
  model: fixed_fractional
  risk_per_trade: 0.015
  max_positions: 1 # Single position only
  tp_rr: 3.0
  sl_atr_multiple: 1.5
  enable_trailing_stop: false

# ---------- Execution (Ultra-minimal) ----------
execution:
  slippage_model: linear
  slippage_bps: 2.0
  commission_rate: 0.0004
  dump_events: false
  export_data_for_viz: false
  enable_latency_profiling: false
  enable_memory_tracking: false
  log_level: "WARNING" # Minimal logging

# ---------- Aggregation (Simplified) ----------
aggregation:
  source_tf_minutes: 5
  target_timeframes_minutes: [60, 240] # Removed 1440
  buffer_size: 500 # Much smaller buffer
  roll_from: "calendar"
  out_of_order_policy: "drop"
  max_clock_skew_seconds: 300
  enable_strict_ordering: false
  fill_missing: ffill

# ---------- Indicators (Minimal) ----------
indicators:
  ema:
    periods: [21, 50] # Removed 200 EMA
    source: close

  atr:
    period: 14

  volume_sma:
    period: 20

# ---------- Detectors (Simplified) ----------
detectors:
  fvg:
    enabled: true
    min_gap_atr: 0.3
    min_gap_pct: 0.015
    min_rel_vol: 0.75
    max_age_minutes: 720 # Reduced from 1440
    enabled_timeframes: ["60", "240"] # Removed 1440

  pivot:
    enabled: false

# ---------- HLZ (Ultra-simplified) ----------
hlz:
  min_members: 2
  min_strength: 1.5
  tf_weight:
    "60": 1.0
    "240": 2.0 # Reduced weight
  merge_tolerance: 0.3
  side_mixing: false
  max_active_hlzs: 50 # Much smaller
  recompute_on_update: false

# ---------- Zone Watcher (Ultra-simplified) ----------
zone_watcher:
  price_tolerance: 0.1
  confirm_closure: false
  min_strength: 0.7
  max_active_zones: 50 # Much smaller

# ---------- Signal candidate pipeline (Simplified) ----------
candidate:
  expiry_minutes: 60 # Reduced
  min_entry_spacing_minutes: 45
  global_min_entry_spacing: 10
  enable_spacing_throttle: true
  filters:
    ema_alignment: false # Disabled for speed
    ema_tolerance_pct: 0.002
    linger_minutes: 30 # Reduced
    reclaim_requires_ema: false # Disabled
    volume_multiple: 0.0 # Disabled
    use_enhanced_killzone: false
    killzone: [] # Disabled
    regime: ["bull", "neutral", "bear"] # Accept all

# ---------- Pool registry (Ultra-simplified) ----------
pools:
  "60":
    ttl: 2h # Much shorter
    hit_tolerance: 0.0
  "240":
    ttl: 12h # Much shorter
    hit_tolerance: 0.0

  strength_threshold: 0.3
  grace_period_minutes: 30 # Reduced
  max_pools_per_tf: 100 # Much smaller
  auto_expire_interval: "5m" # Less frequent

# ---------- Pivot Pools (Simplified) ----------
pivot_pools:
  "60":
    ttl: 6h
    hit_tolerance: 0.0
    min_atr_distance: 0.8
  "240":
    ttl: 1d
    hit_tolerance: 0.0
    min_atr_distance: 1.0

  strength_threshold: 0.5
  grace_period_minutes: 10
  max_pools_per_tf: 100
  auto_expire_interval: "5m"

# ---------- Confluence (Minimal) ----------
confluence:
  min_score: 1 # Reduced threshold
  factors:
    fvg_touch: 1
    pivot_level: 1
    ema_alignment: 0 # Disabled
    volume_spike: 0 # Disabled
